export const RepoActionTypes = {
  TYPE_FETCH_REPO_DATA_START: "TYPE_FETCH_REPO_DATA_START",
  TYPE_FETCH_REPO_DATA_SUCCESS: "TYPE_FETCH_REPO_DATA_SUCCESS",
  TYPE_FETCH_REPO_DATA_FAILURE: "TYPE_FETCH_REPO_DATA_FAILURE",
};
